version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

brews:
  - repository:
      owner: codechenx
      name: homebrew-tv
    commit_author:
      name: codechenx
      email: codechenx@gmail.com
    description: "Fast, feature-rich CSV/TSV/delimited file viewer for the command line"
    homepage: https://github.com/codechenx/tv
    license: MIT
    install: |
      bin.install "tv"
    test: |
      system "#{bin}/tv", "--version"

nfpms:
  - maintainer: codechenx <codechenx@gmail.com>
    description: "Fast, feature-rich CSV/TSV/delimited file viewer for the command line"
    homepage: https://github.com/codechenx/tv
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

scoops:
  - repository:
      owner: codechenx
      name: scoop-bucket
    commit_author:
      name: codechenx
      email: codechenx@gmail.com
    description: "Fast, feature-rich CSV/TSV/delimited file viewer for the command line"
    homepage: https://github.com/codechenx/tv
    license: MIT

snapcrafts:
  - name: codechenx-tv
    summary: Table viewer for terminal
    description: Fast, feature-rich CSV/TSV/delimited file viewer for the command line
    grade: stable
    confinement: strict
    publish: true
    license: MIT
