name: codechenx-tv
 
version: '0.5.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: tv(Table Viewer) for delimited file in terminal
description: |
    tv is a tool to view the delimited file in terminal.
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
parts:
  codechenx-tv:
    plugin: go
    go-importpath: https://github.com/codechenx/tv
    source: https://github.com/codechenx/tv.git
    source-type: git
    build-packages:
      - gcc
apps:
  codechenx-tv:
    command: bin/tv
    plugs:
      - home
      - removable-media
