on: 
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
    release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: 846a7eb801a687d2d239ceedfa76fd7d4e8937dd
        GOARCH: "386"
        GOOS: linux
